apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-c
  name: gamma
  namespace: team-c
spec:
  replicas: 10
  selector:
    matchLabels:
      app: team-c-workload
  template:
    metadata:
      labels:
        app: team-c-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 100mi
            memory: 256Mi
        command:
        - /bin/sh
        - -c
        - stress --vm 2 --vm-bytes 128M
