apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-a
  name: alpha
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-a-workload
  template:
    metadata:
      labels:
        app: team-a-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        command:
        - /bin/sh
        - -c
        - timeout 3000 stress --vm 1 --vm-bytes 2048M