apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-b
  name: beta
  namespace: team-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-b-workload
  template:
    metadata:
      labels:
        app: team-b-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 2
            memory: 256Mi
        command:
        - /bin/sh
        - -c
        - timeout 3000s stress --vm 1 --vm-bytes 1024M