apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-d
  name: delta
  namespace: team-d
spec:
  replicas: 5
  selector:
    matchLabels:
      app: team-d-workload
  template:
    metadata:
      labels:
        app: team-d-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        command:
        - /bin/sh
        - -c
        - stress --vm 1 --vm-bytes 2048M
