apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gamma-hpa
  namespace: team-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gamma
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
