apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-c
  name: gamma
  namespace: team-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-c-workload
  template:
    metadata:
      labels:
        app: team-c-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        command:
        - /bin/sh
        - -c
        - stress --vm 1 --vm-bytes 512M
