apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-b
  name: team-b-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-b-workload
  template:
    metadata:
      labels:
        app: team-b-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 0.5
            memory: 128Mi