apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-a
  name: alpha-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-a-workload
  template:
    metadata:
      labels:
        app: team-a-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 0.5
            memory: 128Mi
        command:
        - /bin/sh
        - -c
        - stress --cpu 4 --vm 1 --vm-bytes 1024