apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: team-d
  name: team-d-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-d-workload
  template:
    metadata:
      labels:
        app: team-d-workload
    spec:
      containers:
      - image: progrium/stress
        name: stress
        resources:
          requests:
            cpu: 1
            memory: 256Mi
        command:
        - /bin/sh
        - -c
        - stress --cpu 2